import flet as ft

#-------PALETA DE COLORES-------
COLOR_BG_DARK = "#0A1A2F"         #FONDO PRINCIPAL
COLOR_BG_CARD = "#16263F"         #TARJETAS Y CONTENEDORES
COLOR_BORDER = "#22314D"          #BORDES
COLOR_GOLD = "#D4AF37"            #BOTONES Y ACENTOS PRINCIPALES
COLOR_GOLD_HOVER = "#B8860B"      #BOTONES
COLOR_TEXT_PRIMARY = "#F5F2E9"    #TEXTO
COLOR_TEXT_SECONDARY = "#848F98"  #DESCRIPCIONES


#-------FUENTES-------
FOND_BRAND = "Cinzel"
FONT_HEADING = "Cormorant"
FONT_BODY = "Montserrat"